version: "3.8"

services:
  ai-jam-postgres-db:
    image: postgres:15.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: harmonicjam
      POSTGRES_HOST_AUTH_METHOD: trust
      PG_LOG_MIN_MESSAGES: warning
    volumes:
      - ai-jam-postgres-data:/var/lib/postgresql/data
      - ./app/db:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"

  ai-jam-web-api:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
      - 5678:5678
    command:
      [
        "python",
        "-m",
        "debugpy",
        "--listen",
        "0.0.0.0:5678",
        "-m",
        "uvicorn",
        "main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--reload",
      ]
    depends_on:
      - ai-jam-postgres-db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@ai-jam-postgres-db:5432/harmonicjam

volumes:
  ai-jam-postgres-data:
