version: "3.8"

services:
  ai-jam-postgres-db:
    image: postgres:15.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: harmonicjam
      POSTGRES_HOST_AUTH_METHOD: trust
      PG_LOG_MIN_MESSAGES: warning
    volumes:
      - ai-jam-postgres-data:/var/lib/postgresql/data
      - ./app/db:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"

  ai-jam-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ai-jam-elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  ai-jam-web-api:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
      - 5678:5678
    env_file:
      - ./.env
    command:
      [
        "python",
        "-m",
        "debugpy",
        "--listen",
        "0.0.0.0:5678",
        "-m",
        "uvicorn",
        "main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--reload",
      ]
    depends_on:
      - ai-jam-postgres-db
      - ai-jam-elasticsearch
    environment:
      DATABASE_URL: postgresql://postgres:postgres@ai-jam-postgres-db:5432/harmonicjam
      ELASTICSEARCH_URL: http://ai-jam-elasticsearch:9200

volumes:
  ai-jam-postgres-data:
  ai-jam-elasticsearch-data:
